CREATE TABLE IF NOT EXISTS EMPLOYEE (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255),
  ROLE VARCHAR(255),
  EMAIL VARCHAR(255)
);

INSERT INTO EMPLOYEE (NAME, ROLE, EMAIL) VALUES ('Charlie', 'Manager', 'charlie@example.com');
